# Generated by Django 5.2.15 on 2026-06-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pieces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicelog",
            name="achieved_tempo",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
