# Generated by Django 5.2.15 on 2026-06-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pieces", "0004_piece_profile_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="trickybit",
            name="key_signature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— none —"),
                    ("C", "C major"),
                    ("G", "G major (1♯)"),
                    ("D", "D major (2♯)"),
                    ("A", "A major (3♯)"),
                    ("E", "E major (4♯)"),
                    ("B", "B major (5♯)"),
                    ("F#", "F♯ major (6♯)"),
                    ("C#", "C♯ major (7♯)"),
                    ("F", "F major (1♭)"),
                    ("Bb", "B♭ major (2♭)"),
                    ("Eb", "E♭ major (3♭)"),
                    ("Ab", "A♭ major (4♭)"),
                    ("Db", "D♭ major (5♭)"),
                    ("Gb", "G♭ major (6♭)"),
                    ("Cb", "C♭ major (7♭)"),
                    ("Am", "A minor"),
                    ("Em", "E minor (1♯)"),
                    ("Bm", "B minor (2♯)"),
                    ("F#m", "F♯ minor (3♯)"),
                    ("C#m", "C♯ minor (4♯)"),
                    ("G#m", "G♯ minor (5♯)"),
                    ("D#m", "D♯ minor (6♯)"),
                    ("A#m", "A♯ minor (7♯)"),
                    ("Dm", "D minor (1♭)"),
                    ("Gm", "G minor (2♭)"),
                    ("Cm", "C minor (3♭)"),
                    ("Fm", "F minor (4♭)"),
                    ("Bbm", "B♭ minor (5♭)"),
                    ("Ebm", "E♭ minor (6♭)"),
                    ("Abm", "A♭ minor (7♭)"),
                ],
                default="",
                max_length=4,
            ),
        ),
    ]
