services:
  web:
    build: .
    restart: unless-stopped
    container_name: practice-web
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    networks:
      - nginx-proxy
    volumes:
      - sqlite_data:/app/data
      - media_data:/app/media
    expose:
      - "8000"

volumes:
  sqlite_data:
  media_data:

networks:
  nginx-proxy:
    external: true
