# Generated by Django 5.2.15 on 2026-06-24 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pieces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "target_features",
                    models.JSONField(
                        default=list,
                        help_text="List of feature_type codes this exercise targets.",
                    ),
                ),
                ("difficulty", models.PositiveSmallIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="PassageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("claude_vision", "Claude Vision AI"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("raw_response", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tricky_bit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="pieces.trickybit",
                    ),
                ),
            ],
            options={
                "verbose_name": "passage analysis",
                "verbose_name_plural": "passage analyses",
            },
        ),
        migrations.CreateModel(
            name="DetectedFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("register_low", "Low register (below C4)"),
                            ("register_middle", "Middle register (C4–C6)"),
                            ("register_high", "High register (C6+)"),
                            ("register_altissimo", "Altissimo (C7+)"),
                            ("interval_stepwise", "Stepwise motion"),
                            ("interval_thirds", "Thirds"),
                            ("interval_fourths_fifths", "Fourths / fifths"),
                            ("interval_sixths", "Sixths"),
                            ("interval_octaves", "Octaves"),
                            ("interval_wide_leaps", "Wide leaps (> octave)"),
                            ("technique_slur", "Slurs / legato"),
                            ("technique_staccato", "Staccato"),
                            ("technique_trill", "Trill"),
                            ("technique_flutter", "Flutter tongue"),
                            ("technique_harmonic", "Harmonics"),
                            ("technique_multiphonic", "Multiphonics"),
                            ("technique_vibrato", "Vibrato notation"),
                            ("rhythm_fast_runs", "Fast scalar runs"),
                            ("rhythm_triplets", "Triplets"),
                            ("rhythm_dotted", "Dotted rhythms"),
                            ("rhythm_syncopation", "Syncopation"),
                            ("rhythm_cross_rhythm", "Cross rhythms / hemiola"),
                            ("mark_accent", "Accents (>)"),
                            ("mark_tenuto", "Tenuto (—)"),
                            ("mark_marcato", "Marcato (^)"),
                            ("dynamic_soft", "Soft dynamics (pp / p)"),
                            ("dynamic_loud", "Loud dynamics (ff / f)"),
                            ("dynamic_sudden_change", "Sudden dynamic changes"),
                            ("key_many_sharps", "Many sharps (3+)"),
                            ("key_many_flats", "Many flats (3+)"),
                            ("time_compound", "Compound time (6/8, 9/8)"),
                            ("time_irregular", "Irregular meter (5/4, 7/8)"),
                            ("time_changing", "Changing time signatures"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_features",
                        to="omr.passageanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["feature_type"],
                "unique_together": {("analysis", "feature_type")},
            },
        ),
    ]
