# Generated by Django 5.2.15 on 2026-06-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_fix_brass_midi_low"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="scale_weights",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
