# Generated by Django 5.2.15 on 2026-06-29 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_profile_scale_weights"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransitionPractice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_low", models.PositiveSmallIntegerField()),
                ("note_high", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("queued", "Queued"),
                            ("retired", "Retired"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "current_tempo",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "fastest_tempo",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "desired_tempo",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_practices",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "position", "created_at"],
                "unique_together": {("profile", "note_low", "note_high")},
            },
        ),
        migrations.CreateModel(
            name="TransitionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_sessions",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TransitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_id", models.CharField(max_length=10)),
                ("rating", models.PositiveSmallIntegerField()),
                (
                    "achieved_tempo",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transition_practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="transitions.transitionpractice",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="transitions.transitionsession",
                    ),
                ),
            ],
            options={
                "ordering": ["logged_at"],
            },
        ),
    ]
