# Generated by Django 5.2.15 on 2026-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scales", "0003_seed_ameb_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="scalepractice",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
