# Generated by Django 5.2.15 on 2026-06-24 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LongToneSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "focus",
                    models.CharField(
                        choices=[
                            ("steadiness", "Steadiness"),
                            ("intonation", "Intonation"),
                            ("crescendo", "Crescendo"),
                            ("decrescendo", "Decrescendo"),
                            ("body_scan", "Body Scan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("use_drone", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="long_tone_sessions",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LongToneLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("midi", models.PositiveSmallIntegerField()),
                ("note_name", models.CharField(max_length=8)),
                ("rating", models.PositiveSmallIntegerField()),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="longtones.longtonesession",
                    ),
                ),
            ],
            options={
                "ordering": ["logged_at"],
            },
        ),
    ]
